#!/usr/bin/env bash
# installing nginx Web servers are the piece of software generating and serving HTML pages

apt-get update
apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
