#!/bin/bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

sudo apt update
sudo apt install -y nginx
sudo sed -i 's@location / {.*@location /redirect_me { return 301 https://www.example.com/; }@' /etc/nginx/sites-available/default
sudo nginx -t

sudo systemctl reload nginx
