#!/bin/bash

# Trap the SIGUSR1 signal to stop the infinite loop
trap 'echo "Terminated"; exit' SIGUSR1

# Display "To infinity and beyond" indefinitely
while :; do
    echo "To infinity and beyond"
    sleep 2
done
