#!/usr/bin/env bash
# This script kills the process 7-highlander.

# Find the PID of the 7-highlander process
process_pid=$(pgrep -f "7-highlander")

# Check if the process is running
if [ -n "$process_pid" ]; then
  # Send SIGKILL signal to forcefully terminate the process
  kill -9 "$process_pid"
  echo "Killed"
fi
