#!/usr/bin/env bash
# This script displays the username, user id, and home directory path for each user in /etc/passwd.

file="/etc/passwd"

while IFS=":" read -r username uid gid info home shell; do
    echo "$username:$uid:$home"
done < "$file"
